name: Publish
run-name: Publication triggered by ${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
  schedule:
    - cron: '36 5 * * 3'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - id: checkout_repository_step
        name: Checkout Git Repository
        uses: actions/checkout@v3
      - id: docker_login_step
        name: Login to Docker
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: build_image_step
        name: Build Docker Image
        run: sh build.sh
      - id: push_image_step
        name: Publish Docker Image
        run: sh docker_push.sh        
